Start testing of control: 0

PLAY [Kubernetes Recovery Testing] *********************************************

TASK [Gathering Facts] *********************************************************
ok: [192.168.1.106]
ok: [192.168.1.101]
ok: [192.168.1.102]
ok: [192.168.1.100]

TASK [Set fact for the hostname at the given index] ****************************
fatal: [192.168.1.106]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'list object' has no attribute '0'. 'list object' has no attribute '0'\n\nThe error appears to be in '/home/parallels/Documents/projects/iot-edge/src/ansible/playbooks/reliability-test.yaml': line 6, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n    - name: Set fact for the hostname at the given index\n      ^ here\n"}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
192.168.1.100              : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
192.168.1.101              : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
192.168.1.102              : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
192.168.1.106              : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   


PLAY [k-bench derive data from results] ****************************************

TASK [List of test names] ******************************************************
ok: [192.168.1.113]

TASK [Display start and end time] **********************************************
ok: [192.168.1.113] => {
    "msg": " - "
}

TASK [Generating CSV file CPU] *************************************************
fatal: [192.168.1.113]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python3"}, "changed": true, "cmd": ["mongoexport", "--db=netdata", "--collection=metrics", "--type=csv", "--fields=hostname,value,timestamp", "--query={\"chart_type\": \"system\", \"chart_family\": \"cpu\", \"chart_context\": \"system.cpu\", \"id\": \"idle\", \"timestamp\": {\"$gt\": , \"$lt\":  }}", "--out=./test-results/reliability-control-1-cpu.csv"], "delta": "0:00:00.010046", "end": "2023-12-26 12:06:20.551833", "msg": "non-zero return code", "rc": 1, "start": "2023-12-26 12:06:20.541787", "stderr": "2023-12-26T12:06:20.551+0200\tquery '[123 34 99 104 97 114 116 95 116 121 112 101 34 58 32 34 115 121 115 116 101 109 34 44 32 34 99 104 97 114 116 95 102 97 109 105 108 121 34 58 32 34 99 112 117 34 44 32 34 99 104 97 114 116 95 99 111 110 116 101 120 116 34 58 32 34 115 121 115 116 101 109 46 99 112 117 34 44 32 34 105 100 34 58 32 34 105 100 108 101 34 44 32 34 116 105 109 101 115 116 97 109 112 34 58 32 123 34 36 103 116 34 58 32 44 32 34 36 108 116 34 58 32 32 125 125]' is not valid JSON: invalid character ',' looking for beginning of value\n2023-12-26T12:06:20.551+0200\ttry 'mongoexport --help' for more information", "stderr_lines": ["2023-12-26T12:06:20.551+0200\tquery '[123 34 99 104 97 114 116 95 116 121 112 101 34 58 32 34 115 121 115 116 101 109 34 44 32 34 99 104 97 114 116 95 102 97 109 105 108 121 34 58 32 34 99 112 117 34 44 32 34 99 104 97 114 116 95 99 111 110 116 101 120 116 34 58 32 34 115 121 115 116 101 109 46 99 112 117 34 44 32 34 105 100 34 58 32 34 105 100 108 101 34 44 32 34 116 105 109 101 115 116 97 109 112 34 58 32 123 34 36 103 116 34 58 32 44 32 34 36 108 116 34 58 32 32 125 125]' is not valid JSON: invalid character ',' looking for beginning of value", "2023-12-26T12:06:20.551+0200\ttry 'mongoexport --help' for more information"], "stdout": "", "stdout_lines": []}

PLAY RECAP *********************************************************************
192.168.1.113              : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

